# Copyright (c) 2025, guimochila.com. Continuous Learning.

severity:
  default-severity: error

output:
  formats:
    - format: sarif
      path: golangci-lint.sarif
    - format: colored-line-number
      path: stderr
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  # Run only fast linters from enabled linters set (first run won't be fast)
  fast: true
  # enable-all: false
  # disable-all: false

  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - gofumpt
    - goheader
    - revive
    - gosec
    - errname

  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    - depguard
    - gomoddirectives
    - tagliatelle
    - testpackage

linters-settings:
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 200
  godox:
    keywords: ['BUG', 'FIXME']
  gofumpt:
    module-path: github.com/guimochila/social
  goheader:
    values:
      const:
        COMPANY: guimochila.com
    template: |-
      Copyright (c) {{ YEAR-2024- }}, {{ COMPANY }}. Continous Learning.
  gosec:
    exclude-generated: true
  funlen:
    ignore-comments: true
    # Does not support severity setting
    lines: -1
    statements: 50
  lll:
    line-length: 120
    tab-width: 2
  revive:
    ignore-generated-header: true
    severity: error
    confidence: 0.8
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        exclude: ['']
        arguments:
          - ['ID'] # AllowList
          - ['VM'] # DenyList
          - - upperCaseConst: true # Extra parameter (upperCaseConst|skipPackageNameChecks)

issues:
  exclude-use-default: true
  exclude-case-sensitive: false
  new: false
  fix: false
  exclude-dirs:
    - 'deployments'
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
